repos:
  - repo: https://github.com/cpp-linter/cpp-linter-hooks
    rev: 2a92e91720ca4bc79d67c3e4aea57642f598d534
    hooks:
      - id: clang-format
        args: [--style=file, --version=15]  # to load .clang-format
      - id: clang-tidy
        args: [--checks=.clang-tidy, --version=15] # path/to/.clang-tidy
