name: CodSpeed

on:
  push:
    branches:
      - "main"
    paths:
      - "cpp-linter-hooks/**"
      - "tests/**"
      - ".github/workflows/codspeed.yml"
      - "pyproject.toml"
  pull_request:
    branches:
      - "main"
    paths:
      - "cpp-linter-hooks/**"
      - "tests/**"
      - ".github/workflows/codspeed.yml"
      - "pyproject.toml"
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  #v5
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c #v5
        with:
          python-version: "3.13"

      - name: Setup uv
        uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0

      - name: Install dependencies
        run: uv sync --dev

      - name: Run benchmarks
        uses: CodSpeedHQ/action@0700edb451d0e9f2426f99bd6977027e550fb2a6 #v3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: uv run pytest tests/ --codspeed
          mode: instrumentation
