name: E2E Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        clang_version: [16, 17, 18, 19, 20, 21]
        clang_style: [LLVM, Google, Chromium, Mozilla, WebKit]

    name: Test clang ${{ matrix.clang_version }} with style ${{ matrix.clang_style }}
    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: cloudwu/ltask

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit

      - name: Install pre-commit hooks and run
        run: |
          rm -f .pre-commit-config.yaml || true
          cat > .pre-commit-config.yaml << EOF
          repos:
            - repo: https://github.com/cpp-linter/cpp-linter-hooks
              rev: ${{ github.sha }}
              hooks:
                - id: clang-format
                  args: [--style=${{ matrix.clang_style }}, --version=${{ matrix.clang_version }}]
          EOF

          pre-commit install
          pre-commit run -v --all-files
        continue-on-error: true
