name: E2E Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        clang_version: [16, 17, 18, 19, 20, 21]

    name: Test clang ${{ matrix.clang_version }}
    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit

      - name: Install pre-commit hooks and run
        run: |
          rm -f .pre-commit-config.yaml || true
          cat > .pre-commit-config.yaml << EOF
          repos:
            - repo: https://github.com/pre-commit/mirrors-clang-format
              rev: ${{ matrix.clang_version }}
              hooks:
                - id: clang-format
                  args: [--style=LLVM, --version=${{ matrix.clang_version }}]
          EOF

          pre-commit install
          pre-commit run -v --all-files
